'use client'
import { useEffect, useMemo, useState } from 'react'
import type maplibregl from 'maplibre-gl'

/* ============================================================
   CWY · Wake-Vortex Decay & Encounter Predictor
   ------------------------------------------------------------
   Pairwise leader-follower wake-encounter scorer that models
   counter-rotating vortex pair generated by each leader using
   Burnham-Hallock tangential velocity profile, applies temporal
   decay per Sarpkaya-Greene atmospheric-stability model (eddy
   dissipation rate / N-stratification), advects the wake tube
   along leader track with ambient wind, applies typical sink
   rate (b0/2 * V_wake per Spalart 1998), and tests each
   trailing target for entry into the predicted vortex tube
   within a configurable look-ahead. Outputs Γ_resid, encounter
   tube radius, vertical offset to vortex core, and rolling-
   moment coefficient estimate per Hinton-Tatnall.

   Distinct from:
     - RECAT-EU wake (regulatory minima at gate/runway only)
     - Wake display (purely visual icon)
     - TBS (HW-compressed time-based separation)

   References:
   FAA AC 90-23G Aircraft Wake Turbulence
   FAA Order JO 7110.65 §5-5 wake-turbulence sep
   FAA RECAT-1.5 / RECAT-EU ed.3 wake categorisation
   ICAO Doc 4444 PANS-ATM §5.8 wake separation
   ICAO Doc 9426 ATS Planning Manual III §3 wake encounters
   EUROCONTROL EUROWAKE / Wake Vortex Specification ed.2.0
   EUROCONTROL CREDOS Crosswind-Reduced-Sep operational concept
   DLR WakeNet3-Europe Final Report 2013 §4 decay models
   NASA TM-2008-215534 wake-vortex hazard model
   NASA TP-1976-1465 Hallock-Burnham vortex profile
   Sarpkaya, J. Aircraft 1998 §6 atmospheric decay
   Spalart, ARFM 1998 §3 sink rate b0/2 V_wake
   Hinton & Tatnall, NASA TM-1997-4768 rolling-moment
   Holzäpfel, J. Aircraft 2003 P2P probabilistic model
   Crow, AIAA 1970 long-wave instability
   NTSB AAR-02-01 American 587 KJFK A300 wake-induced rudder
   ============================================================ */

interface SFlight {
  icao: string; callsign?: string; type?: string; operator?: string; category?: string
  lat: number; lng: number; altitudeFt: number; velocityKts: number; track: number; vertRate: number; ground: boolean
}
interface Props { map: maplibregl.Map | null; flights: SFlight[]; onClose: () => void; onFly: (icao: string) => void }

type Tier = 'SEVERE' | 'MOD-PLUS' | 'MODERATE' | 'LIGHT' | 'TRACE' | 'IDLE'
const TIER_COLOR: Record<Tier, string> = {
  SEVERE: '#ef4444', 'MOD-PLUS': '#f43f5e', MODERATE: '#f59e0b', LIGHT: '#0ea5e9', TRACE: '#10b981', IDLE: '#64748b',
}
const TIER_ORDER: Tier[] = ['SEVERE','MOD-PLUS','MODERATE','LIGHT','TRACE']
const TIER_RANK: Record<Tier, number> = { SEVERE: 0, 'MOD-PLUS': 1, MODERATE: 2, LIGHT: 3, TRACE: 4, IDLE: 5 }

// RECAT-EU style leader classes with b0 (initial vortex spacing in m = π/4 * wingspan)
type WakeClass = 'SUPER' | 'UHVY' | 'HVY' | 'UMED' | 'LMED' | 'LIGHT'
interface WakeParams { mass: number; span: number; b0: number; gamma0: number } // mass kg, span m
const WAKE_CLASS: Record<WakeClass, WakeParams> = {
  SUPER: { mass: 575000, span: 80,  b0: 62.8, gamma0: 0 }, // A380
  UHVY:  { mass: 350000, span: 65,  b0: 51.0, gamma0: 0 },
  HVY:   { mass: 230000, span: 60,  b0: 47.1, gamma0: 0 },
  UMED:  { mass: 80000,  span: 36,  b0: 28.3, gamma0: 0 },
  LMED:  { mass: 40000,  span: 28,  b0: 22.0, gamma0: 0 },
  LIGHT: { mass: 7000,   span: 16,  b0: 12.6, gamma0: 0 },
}
const CLASS_COLOR: Record<WakeClass, string> = {
  SUPER: '#a855f7', UHVY: '#ef4444', HVY: '#f43f5e', UMED: '#f59e0b', LMED: '#0ea5e9', LIGHT: '#10b981',
}

// Wake-vortex constants (SI)
const RHO_SL = 1.225
const G = 9.81
const KT_MS = 0.5144
const FT_M = 0.3048
const NM_M = 1852

function haversineNm(la1: number, lo1: number, la2: number, lo2: number): number {
  const R = 3440.065
  const φ1 = la1 * Math.PI / 180, φ2 = la2 * Math.PI / 180
  const dφ = (la2 - la1) * Math.PI / 180, dλ = (lo2 - lo1) * Math.PI / 180
  const a = Math.sin(dφ/2)**2 + Math.cos(φ1)*Math.cos(φ2)*Math.sin(dλ/2)**2
  return 2 * R * Math.asin(Math.sqrt(a))
}
function bearingDeg(la1: number, lo1: number, la2: number, lo2: number): number {
  const φ1 = la1 * Math.PI / 180, φ2 = la2 * Math.PI / 180
  const dλ = (lo2 - lo1) * Math.PI / 180
  const y = Math.sin(dλ) * Math.cos(φ2)
  const x = Math.cos(φ1)*Math.sin(φ2) - Math.sin(φ1)*Math.cos(φ2)*Math.cos(dλ)
  return (Math.atan2(y, x) * 180 / Math.PI + 360) % 360
}

function classifyLeader(f: SFlight): WakeClass {
  const t = (f.type || '').toUpperCase()
  if (/A380|A388|A38/.test(t)) return 'SUPER'
  if (/B748|B744|B747|A340|A346|MD11/.test(t)) return 'UHVY'
  if (/B77|B78|B767|A33|A35|A300|A310|MD10|DC10/.test(t)) return 'HVY'
  if (/B73|A32|A21|A22|B75|B71|MD8|MD9|BCS|BCS3|CS|A220|A19/.test(t)) return 'UMED'
  if (/CRJ|E17|E19|E29|E14|E13|E15|EMB|RJ|F70|F100|ATR|DH8|Q40|SF34/.test(t)) return 'LMED'
  if (/C172|C152|C182|SR2|DA4|PA28|PA32|TBM|PC12|BE9|BE3|BE2|J32|J41/.test(t)) return 'LIGHT'
  // weight-based fallback
  if (f.velocityKts > 470) return 'UHVY'
  if (f.velocityKts > 380) return 'HVY'
  if (f.velocityKts > 260) return 'UMED'
  if (f.velocityKts > 180) return 'LMED'
  return 'LIGHT'
}

function airDensity(altFt: number): number {
  // ISA
  const altM = altFt * FT_M
  const T = 288.15 - 0.0065 * altM
  const p = 101325 * Math.pow(T/288.15, 5.2561)
  return p / (287.05 * T)
}

function isaTemp(altFt: number): number {
  const altM = altFt * FT_M
  return 288.15 - 0.0065 * Math.min(altM, 11000)
}

interface Encounter {
  leader: SFlight
  follower: SFlight
  leaderClass: WakeClass
  followerClass: WakeClass
  inTrailNm: number          // along-track distance follower behind leader
  lateralOffsetNm: number    // perpendicular to leader track
  verticalOffsetFt: number   // follower above leader (+)
  ageS: number               // wake age at follower position
  vortexSinkFt: number       // wake has descended this far
  vortexRadiusFt: number     // current wake-tube effective radius
  gammaResid: number         // residual circulation m^2/s
  vTangentialKts: number     // peak induced velocity at follower lateral offset
  rollingMomentCoef: number  // induced rolling moment coefficient
  inTube: boolean            // follower wing inside vortex tube
  closingKts: number
  tier: Tier
  score: number
  drivers: { gamma: number; geom: number; age: number; offset: number; alt: number; closing: number }
  rationale: string
  citation: string
}

export default function CwyWakeEncounter({ map, flights, onClose, onFly }: Props) {
  // sliders
  const [scopeNm, setScopeNm] = useState(15)
  const [horizonS, setHorizonS] = useState(180)
  const [edrCat, setEdrCat] = useState(2)   // 0=calm 1=light 2=moderate 3=strong
  const [bvf, setBvf] = useState(0.012)     // Brunt-Väisälä freq (1/s)
  const [windKt, setWindKt] = useState(8)
  const [windDirDeg, setWindDirDeg] = useState(270)
  const [gammaMul, setGammaMul] = useState(100)
  const [advMul, setAdvMul] = useState(100)

  // toggles
  const [showTube, setShowTube] = useState(true)
  const [showLink, setShowLink] = useState(true)
  const [showHalo, setShowHalo] = useState(true)
  const [showPin, setShowPin] = useState(true)
  const [showLbl, setShowLbl] = useState(true)
  const [showSink, setShowSink] = useState(true)

  const [classFilter, setClassFilter] = useState<Record<WakeClass, boolean>>({ SUPER:true, UHVY:true, HVY:true, UMED:true, LMED:true, LIGHT:true })
  const [tierFilter, setTierFilter] = useState<Tier | 'ALL'>('ALL')
  const [tab, setTab] = useState<'ENCOUNTERS'|'LEADERS'|'CLASSES'>('ENCOUNTERS')
  const [search, setSearch] = useState('')

  const encounters: Encounter[] = useMemo(() => {
    const enc: Encounter[] = []
    const air = flights.filter(f => !f.ground && f.altitudeFt > 100 && f.velocityKts > 40)
    // EDR categories (m^2/s^3)
    const edrVals = [0.001, 0.01, 0.05, 0.15]
    const edr = edrVals[edrCat] || 0.05

    for (let i = 0; i < air.length; i++) {
      const lead = air[i]
      const lClass = classifyLeader(lead)
      if (!classFilter[lClass]) continue
      const lp = WAKE_CLASS[lClass]
      const rho = airDensity(lead.altitudeFt)
      // initial circulation Γ0 = M*g / (ρ * V * b0)
      const V = Math.max(50, lead.velocityKts * KT_MS)
      const gamma0 = (lp.mass * G) / (rho * V * lp.b0)
      // characteristic time t* = 2π b0^2 / Γ0
      const tStar = (2 * Math.PI * lp.b0 * lp.b0) / Math.max(1, gamma0)
      // sink speed Vsink = Γ0 / (2π b0)
      const vSink = gamma0 / (2 * Math.PI * lp.b0)   // m/s
      // normalized EDR: ε* = (ε * b0)^(1/3) / wsink
      const epsStar = Math.pow(edr * lp.b0, 1/3) / Math.max(0.1, vSink)
      // normalized stratification N* = N * t*
      const nStar = bvf * tStar

      for (let j = 0; j < air.length; j++) {
        if (i === j) continue
        const foll = air[j]
        const d = haversineNm(lead.lat, lead.lng, foll.lat, foll.lng)
        if (d > scopeNm || d < 0.05) continue
        // along-track / cross-track relative to leader heading
        const brg = bearingDeg(lead.lat, lead.lng, foll.lat, foll.lng)
        const rel = ((brg - lead.track + 540) % 360) - 180
        // follower must be behind leader: rel angle within ±90 from "behind" (180)
        const behindAng = ((rel - 180 + 540) % 360) - 180
        if (Math.abs(behindAng) > 70) continue
        const inTrailNm = d * Math.cos(behindAng * Math.PI/180)
        const lateralNm = d * Math.sin(behindAng * Math.PI/180)
        if (inTrailNm < 0.1 || inTrailNm > scopeNm) continue

        // wake age: leader passed this point at time = inTrail/V_ground
        const Vleader = Math.max(50, lead.velocityKts * KT_MS)
        const ageS = (inTrailNm * NM_M) / Vleader
        if (ageS > horizonS) continue

        // wake advection by wind (cross-track drift after age)
        const windRel = ((windDirDeg - lead.track + 540) % 360) - 180   // wind FROM rel to track
        const windCross = -windKt * KT_MS * Math.sin(windRel * Math.PI/180)  // m/s positive=right of track
        const wakeDriftNm = (windCross * ageS) / NM_M
        const effLatNm = lateralNm - wakeDriftNm

        // vertical sink (Spalart) plus stratification bounce
        const sinkM = vSink * ageS * Math.exp(-Math.min(2, nStar))
        const sinkFt = sinkM / FT_M
        const vertOffsetFt = (foll.altitudeFt - lead.altitudeFt) + sinkFt

        // residual circulation via Sarpkaya 2-phase exponential
        const tauN = ageS / tStar
        const diff = Math.exp(-0.45 * tauN - 0.6 * epsStar * tauN * tauN)
        const stratFactor = Math.exp(-0.5 * nStar * tauN)
        const gammaResid = gamma0 * Math.max(0.02, diff * stratFactor) * (gammaMul/100)

        // vortex tube effective radius (m): r_core ≈ 0.052 b0, but encounter danger envelope = b0/2 expanded by age
        const rCore = 0.052 * lp.b0
        const rEnvM = (lp.b0 / 2) * (1 + 0.4 * tauN)
        const rEnvFt = rEnvM / FT_M

        // Burnham-Hallock tangential velocity at offset from core
        const offM = Math.abs(effLatNm) * NM_M
        const r = Math.max(0.1, offM)
        const vTan = (gammaResid / (2 * Math.PI * r)) * (r*r / (r*r + rCore*rCore))   // m/s
        const vTanKt = vTan / KT_MS

        // follower inside tube?
        const inTube = (Math.abs(effLatNm * NM_M) < rEnvM * 1.2) && (Math.abs(vertOffsetFt * FT_M) < rEnvM * 1.6)

        // rolling-moment coefficient Hinton-Tatnall: Cl_wake ≈ Γ / (V_f * span_f)
        const Vf = Math.max(40, foll.velocityKts * KT_MS)
        const followClass = classifyLeader(foll)
        const fSpan = WAKE_CLASS[followClass].span
        const rollCoef = gammaResid / (Vf * fSpan * 2)

        // closing
        const dV = (lead.velocityKts - foll.velocityKts)
        const closingKts = -dV   // positive if follower catching up

        // drivers (0-100)
        const gammaD = Math.min(100, (gammaResid / Math.max(1, gamma0)) * 100)
        const geomD = inTube ? 95 : Math.max(0, 100 - (Math.abs(effLatNm * NM_M) / rEnvM) * 60)
        const ageD = Math.max(0, 100 - (ageS / 180) * 100)
        const offsetD = Math.max(0, 100 - (Math.abs(vertOffsetFt) / 800) * 100)
        const altD = Math.abs(vertOffsetFt) < 500 ? 80 : Math.abs(vertOffsetFt) < 1000 ? 45 : 15
        const closingD = Math.min(100, Math.max(0, closingKts) * 2)
        const drivers = { gamma: gammaD, geom: geomD, age: ageD, offset: offsetD, alt: altD, closing: closingD }
        const maxD = Math.max(geomD, gammaD, altD)
        const meanD = (gammaD + geomD + ageD + offsetD + altD + closingD) / 6
        let score = (maxD * 0.7 + meanD * 0.3) * (advMul/100)

        // size differential amplifier: small follower behind huge leader
        const sizeRatio = WAKE_CLASS[followClass].mass / lp.mass
        if (sizeRatio < 0.15) score *= 1.18
        else if (sizeRatio < 0.4) score *= 1.08
        score = Math.max(0, Math.min(100, score))

        // tier per AC 90-23G classification & rolling-moment thresholds
        let tier: Tier = 'IDLE'
        if (inTube && Math.abs(rollCoef) > 0.07) tier = 'SEVERE'
        else if (inTube && Math.abs(rollCoef) > 0.04) tier = 'MOD-PLUS'
        else if ((inTube && Math.abs(rollCoef) > 0.02) || (vTanKt > 15 && Math.abs(vertOffsetFt) < 500)) tier = 'MODERATE'
        else if (vTanKt > 8 && Math.abs(vertOffsetFt) < 700) tier = 'LIGHT'
        else if (vTanKt > 3 && Math.abs(vertOffsetFt) < 1000) tier = 'TRACE'

        let rationale = 'wake decayed below detectable threshold'
        let citation = 'AC 90-23G §3'
        if (tier === 'SEVERE') { rationale = `severe wake encounter · Cl ${rollCoef.toFixed(3)} > 0.07 · descend 500ft + offset 1nm upwind`; citation = 'NTSB AAR-02-01 / AC 90-23G §4.3' }
        else if (tier === 'MOD-PLUS') { rationale = `mod-plus rolling moment Cl ${rollCoef.toFixed(3)} · increase trail to ${Math.ceil(inTrailNm + 2)}nm`; citation = 'AC 90-23G §4.3 / JO 7110.65 §5-5' }
        else if (tier === 'MODERATE') { rationale = `moderate ${Math.round(vTanKt)}kt induced · maintain 1000ft vertical / 2nm trail`; citation = 'Doc 4444 §5.8 / AC 90-23G §3' }
        else if (tier === 'LIGHT') { rationale = `light wake ${Math.round(vTanKt)}kt · monitor for momentary upset`; citation = 'EUROCONTROL EUROWAKE §4' }
        else if (tier === 'TRACE') { rationale = `trace ${Math.round(vTanKt)}kt induced · informational`; citation = 'Sarpkaya 1998 §6' }

        enc.push({
          leader: lead, follower: foll, leaderClass: lClass, followerClass: followClass,
          inTrailNm, lateralOffsetNm: effLatNm, verticalOffsetFt: vertOffsetFt,
          ageS, vortexSinkFt: sinkFt, vortexRadiusFt: rEnvFt,
          gammaResid, vTangentialKts: vTanKt, rollingMomentCoef: rollCoef,
          inTube, closingKts, tier, score: Math.round(score), drivers, rationale, citation,
        })
      }
    }
    return enc.sort((a,b) => TIER_RANK[a.tier] - TIER_RANK[b.tier] || b.score - a.score)
  }, [flights, scopeNm, horizonS, edrCat, bvf, windKt, windDirDeg, gammaMul, advMul, classFilter])

  const counts: Record<Tier, number> = useMemo(() => {
    const c: Record<Tier, number> = { SEVERE:0, 'MOD-PLUS':0, MODERATE:0, LIGHT:0, TRACE:0, IDLE:0 }
    encounters.forEach(e => { c[e.tier]++ })
    return c
  }, [encounters])

  const meanScore = encounters.length ? Math.round(encounters.reduce((s,e) => s + e.score, 0) / encounters.length) : 0
  const meanTier: Tier = meanScore >= 75 ? 'SEVERE' : meanScore >= 55 ? 'MOD-PLUS' : meanScore >= 35 ? 'MODERATE' : meanScore >= 18 ? 'LIGHT' : meanScore >= 5 ? 'TRACE' : 'IDLE'
  const worst = encounters[0]
  const tubeEnc = encounters.filter(e => e.inTube).length

  const visible = encounters.filter(e => {
    if (tierFilter !== 'ALL' && e.tier !== tierFilter) return false
    if (search) {
      const s = search.toLowerCase()
      if (![e.leader.callsign, e.leader.icao, e.follower.callsign, e.follower.icao, e.leaderClass, e.followerClass, e.leader.type, e.follower.type].some(v => (v||'').toLowerCase().includes(s))) return false
    }
    return true
  })

  const byLeader = useMemo(() => {
    const m = new Map<string, Encounter[]>()
    encounters.forEach(e => { if (!m.has(e.leader.icao)) m.set(e.leader.icao, []); m.get(e.leader.icao)!.push(e) })
    return [...m.entries()].sort(([,a],[,b]) => TIER_RANK[a[0].tier] - TIER_RANK[b[0].tier] || b[0].score - a[0].score)
  }, [encounters])

  const byClass = useMemo(() => {
    const m = new Map<WakeClass, Encounter[]>()
    encounters.forEach(e => { if (!m.has(e.leaderClass)) m.set(e.leaderClass, []); m.get(e.leaderClass)!.push(e) })
    return [...m.entries()].sort(([a],[b]) => TIER_RANK['IDLE'] - 0)
  }, [encounters])

  // ============ MAP OVERLAY ============
  useEffect(() => {
    if (!map) return
    const m = map
    const SRC = 'cwy-src', LBL = 'cwy-lbl'
    const features: GeoJSON.Feature[] = []
    const labels: GeoJSON.Feature[] = []
    const seenLead = new Set<string>()

    encounters.forEach(e => {
      if (e.tier === 'IDLE') return
      const c = TIER_COLOR[e.tier]
      // leader halo
      if (!seenLead.has(e.leader.icao)) {
        seenLead.add(e.leader.icao)
        if (showHalo) {
          features.push({
            type: 'Feature', geometry: { type: 'Point', coordinates: [e.leader.lng, e.leader.lat] },
            properties: { color: c, kind: 'halo', radius: 8 + Math.min(14, e.score/7) },
          })
        }
        if (showTube) {
          // draw two parallel wake lines behind leader (port/stbd vortex) along reverse track
          const trkRad = (e.leader.track + 180) * Math.PI / 180
          const perpRad = (e.leader.track + 90) * Math.PI / 180
          const lengthNm = Math.min(scopeNm, horizonS * (e.leader.velocityKts/3600))
          const halfBnm = (WAKE_CLASS[e.leaderClass].b0 / 2) / NM_M
          for (const sign of [-1, 1]) {
            const coords: number[][] = []
            for (let k = 0; k <= 24; k++) {
              const distNm = (k/24) * lengthNm
              const baseLat = e.leader.lat + (distNm/60) * Math.cos(trkRad)
              const baseLng = e.leader.lng + (distNm/60) * Math.sin(trkRad) / Math.cos(e.leader.lat * Math.PI/180)
              const offLat = sign * halfBnm * Math.cos(perpRad)
              const offLng = sign * halfBnm * Math.sin(perpRad) / Math.cos(e.leader.lat * Math.PI/180)
              coords.push([baseLng + offLng, baseLat + offLat])
            }
            features.push({ type: 'Feature', geometry: { type: 'LineString', coordinates: coords }, properties: { color: CLASS_COLOR[e.leaderClass], kind: 'tube' } })
          }
        }
      }
      // follower pin
      if (showPin) {
        features.push({
          type: 'Feature', geometry: { type: 'Point', coordinates: [e.follower.lng, e.follower.lat] },
          properties: { color: c, kind: 'follower', radius: 5 },
        })
      }
      if (showLink) {
        features.push({
          type: 'Feature', geometry: { type: 'LineString', coordinates: [[e.leader.lng, e.leader.lat],[e.follower.lng, e.follower.lat]] },
          properties: { color: c, kind: 'link' },
        })
      }
      if (showLbl) {
        labels.push({
          type: 'Feature', geometry: { type: 'Point', coordinates: [e.follower.lng, e.follower.lat] },
          properties: { text: `${e.follower.callsign||e.follower.icao} ‹ ${e.leader.callsign||e.leader.icao} · ${e.tier} · ${Math.round(e.vTangentialKts)}kt`, color: c },
        })
      }
    })
    try {
      if (!m.getSource(SRC)) m.addSource(SRC, { type: 'geojson', data: { type: 'FeatureCollection', features } as GeoJSON.FeatureCollection })
      else (m.getSource(SRC) as maplibregl.GeoJSONSource).setData({ type: 'FeatureCollection', features } as GeoJSON.FeatureCollection)
      if (!m.getSource(LBL)) m.addSource(LBL, { type: 'geojson', data: { type: 'FeatureCollection', features: labels } as GeoJSON.FeatureCollection })
      else (m.getSource(LBL) as maplibregl.GeoJSONSource).setData({ type: 'FeatureCollection', features: labels } as GeoJSON.FeatureCollection)

      if (showTube && !m.getLayer('cwy-tube')) m.addLayer({ id:'cwy-tube', type:'line', source:SRC, filter:['==',['get','kind'],'tube'], paint:{ 'line-color': ['get','color'], 'line-width': 1.5, 'line-dasharray': [2,2], 'line-opacity': 0.7 } })
      if (showLink && !m.getLayer('cwy-link')) m.addLayer({ id:'cwy-link', type:'line', source:SRC, filter:['==',['get','kind'],'link'], paint:{ 'line-color': ['get','color'], 'line-width': 1.2, 'line-dasharray':[1,2], 'line-opacity': 0.8 } })
      if (showHalo && !m.getLayer('cwy-halo')) m.addLayer({ id:'cwy-halo', type:'circle', source:SRC, filter:['==',['get','kind'],'halo'], paint:{ 'circle-color':'transparent', 'circle-stroke-color':['get','color'], 'circle-stroke-width':2, 'circle-radius':['get','radius'], 'circle-opacity': 0.6 } })
      if (showPin && !m.getLayer('cwy-pin')) m.addLayer({ id:'cwy-pin', type:'circle', source:SRC, filter:['==',['get','kind'],'follower'], paint:{ 'circle-color':['get','color'], 'circle-stroke-color':'#0f172a', 'circle-stroke-width':1, 'circle-radius':5 } })
      if (showLbl && !m.getLayer('cwy-lbl')) m.addLayer({ id:'cwy-lbl', type:'symbol', source:LBL, layout:{ 'text-field':['get','text'], 'text-size':9, 'text-offset':[0,1.6], 'text-anchor':'top', 'text-font':['Noto Sans Regular'] }, paint:{ 'text-color':['get','color'], 'text-halo-color':'#0f172a', 'text-halo-width':1.2 } })
    } catch {}
    return () => {
      try {
        for (const id of ['cwy-tube','cwy-link','cwy-halo','cwy-pin','cwy-lbl']) if (m.getLayer(id)) m.removeLayer(id)
        for (const id of [SRC, LBL]) if (m.getSource(id)) m.removeSource(id)
      } catch {}
    }
  }, [map, encounters, showTube, showLink, showHalo, showPin, showLbl, scopeNm, horizonS])

  const tierPill = (t: Tier) => (
    <span className="px-1.5 py-0.5 rounded text-[10px] font-semibold tracking-wide" style={{ background:`${TIER_COLOR[t]}22`, color: TIER_COLOR[t], border:`1px solid ${TIER_COLOR[t]}55` }}>{t}</span>
  )
  const classPill = (c: WakeClass) => (
    <span className="px-1 py-0.5 rounded text-[9px] font-mono" style={{ background:`${CLASS_COLOR[c]}1f`, color: CLASS_COLOR[c], border:`1px solid ${CLASS_COLOR[c]}55` }}>{c}</span>
  )

  // scatter helpers: age vs induced velocity
  const sx = (age: number) => 20 + Math.min(180, age) * 340/180
  const sy = (v: number) => 100 - Math.min(40, v) * 90/40

  return (
    <div className="absolute right-3 top-16 bottom-3 w-[440px] z-[60] rounded-2xl border border-slate-800 bg-slate-950/90 backdrop-blur-md text-slate-200 shadow-2xl flex flex-col overflow-hidden">
      <div className="flex items-center justify-between px-3 py-2 border-b border-slate-800 bg-slate-900/60">
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 rounded-full" style={{ background: TIER_COLOR[meanTier] }} />
          <div className="text-sm font-semibold">CWY · Wake Vortex Encounter</div>
          <span className="text-[10px] text-slate-500">Burnham-Hallock / Sarpkaya</span>
        </div>
        <button onClick={onClose} className="text-slate-400 hover:text-slate-100 text-lg leading-none">×</button>
      </div>

      <div className="grid grid-cols-6 gap-1 px-2 pt-2">
        {(['SEVERE','MOD-PLUS','MODERATE','LIGHT','TRACE'] as Tier[]).map(t => (
          <button key={t} onClick={() => setTierFilter(tierFilter === t ? 'ALL' : t)}
            className={`px-1.5 py-1 rounded border text-[10px] font-semibold tracking-wide transition ${tierFilter===t?'opacity-100':'opacity-70 hover:opacity-100'}`}
            style={{ borderColor: `${TIER_COLOR[t]}55`, background: tierFilter===t?`${TIER_COLOR[t]}22`:'transparent', color: TIER_COLOR[t] }}>
            <div className="text-[8px] opacity-80 truncate">{t}</div>
            <div className="text-sm font-mono">{counts[t]}</div>
          </button>
        ))}
        <button onClick={() => setTierFilter('ALL')} className={`px-1.5 py-1 rounded border text-[10px] tracking-wide ${tierFilter==='ALL'?'bg-sky-500/15 border-sky-500/40 text-sky-300':'border-slate-700 text-slate-400 hover:text-slate-200'}`}>
          <div className="text-[8px]">ALL</div>
          <div className="text-sm font-mono">{encounters.length}</div>
        </button>
      </div>

      <div className="grid grid-cols-3 gap-1 px-2 pt-2 text-[10px]">
        <div className="rounded border border-slate-800 bg-slate-900/40 px-2 py-1">
          <div className="text-slate-500">MEAN</div>
          <div className="font-mono text-sm" style={{ color: TIER_COLOR[meanTier] }}>{meanScore}</div>
        </div>
        <div className="rounded border border-slate-800 bg-slate-900/40 px-2 py-1">
          <div className="text-slate-500">WORST</div>
          <div className="font-mono text-xs truncate" style={{ color: worst ? TIER_COLOR[worst.tier] : '#64748b' }}>{worst ? (worst.follower.callsign || worst.follower.icao) : '—'}</div>
        </div>
        <div className="rounded border border-slate-800 bg-slate-900/40 px-2 py-1">
          <div className="text-slate-500">IN-TUBE</div>
          <div className="font-mono text-sm text-rose-400">{tubeEnc}</div>
        </div>
        <div className="rounded border border-slate-800 bg-slate-900/40 px-2 py-1">
          <div className="text-slate-500">SEVERE</div>
          <div className="font-mono text-sm text-rose-400">{counts.SEVERE}</div>
        </div>
        <div className="rounded border border-slate-800 bg-slate-900/40 px-2 py-1">
          <div className="text-slate-500">LEADERS</div>
          <div className="font-mono text-sm text-sky-300">{new Set(encounters.map(e => e.leader.icao)).size}</div>
        </div>
        <div className="rounded border border-slate-800 bg-slate-900/40 px-2 py-1">
          <div className="text-slate-500">PAIRS</div>
          <div className="font-mono text-sm">{encounters.length}</div>
        </div>
      </div>

      {/* Scatter: age vs induced velocity */}
      <div className="px-2 pt-2">
        <svg viewBox="0 0 380 110" className="w-full h-[110px] rounded border border-slate-800 bg-slate-900/40">
          <rect x={20} y={sy(15)} width={340} height={sy(0)-sy(15)} fill="#0ea5e918" />
          <rect x={20} y={sy(25)} width={340} height={sy(15)-sy(25)} fill="#f59e0b1a" />
          <rect x={20} y={10} width={340} height={sy(25)-10} fill="#ef44441a" />
          <line x1={20} y1={sy(15)} x2={360} y2={sy(15)} stroke="#0ea5e9" strokeDasharray="2 2" strokeOpacity={0.5} />
          <line x1={20} y1={sy(25)} x2={360} y2={sy(25)} stroke="#f59e0b" strokeDasharray="2 2" strokeOpacity={0.5} />
          {encounters.map((e, i) => (
            <circle key={i} cx={sx(e.ageS)} cy={sy(e.vTangentialKts)} r={2.5} fill={TIER_COLOR[e.tier]} opacity={0.85} />
          ))}
          <text x={4} y={14} fill="#64748b" fontSize={8} fontFamily="monospace">v-tan kt</text>
          <text x={360} y={108} fill="#64748b" fontSize={8} fontFamily="monospace" textAnchor="end">age s</text>
        </svg>
      </div>

      {/* Sliders */}
      <div className="grid grid-cols-2 gap-1 px-2 pt-2 text-[10px]">
        {([
          ['SCOPE', scopeNm, setScopeNm, 3, 30, 'nm'],
          ['HORIZON', horizonS, setHorizonS, 30, 360, 's'],
          ['EDR', edrCat, setEdrCat, 0, 3, ''],
          ['B-V N×1000', Math.round(bvf*1000), (v:number)=>setBvf(v/1000), 0, 30, ''],
          ['WIND', windKt, setWindKt, 0, 60, 'kt'],
          ['WIND-DIR', windDirDeg, setWindDirDeg, 0, 359, '°'],
          ['Γ-MUL', gammaMul, setGammaMul, 50, 200, '%'],
          ['ADV-MUL', advMul, setAdvMul, 50, 200, '%'],
        ] as Array<[string, number, (n:number)=>void, number, number, string]>).map(([label, val, set, min, max, unit]) => (
          <label key={label} className="flex flex-col gap-0.5 rounded border border-slate-800 bg-slate-900/40 px-2 py-1">
            <span className="text-slate-500 flex justify-between"><span>{label}</span><span className="font-mono text-slate-200">{val}{unit}</span></span>
            <input type="range" min={min} max={max} value={val} onChange={e=>set(Number(e.target.value))} className="w-full accent-sky-500" />
          </label>
        ))}
      </div>

      <div className="flex flex-wrap gap-1 px-2 pt-2">
        {(['SUPER','UHVY','HVY','UMED','LMED','LIGHT'] as WakeClass[]).map(c => (
          <button key={c} onClick={() => setClassFilter(f => ({ ...f, [c]: !f[c] }))}
            className={`px-1.5 py-0.5 rounded text-[10px] font-mono border transition ${classFilter[c]?'opacity-100':'opacity-40'}`}
            style={{ background:`${CLASS_COLOR[c]}1f`, color: CLASS_COLOR[c], borderColor: `${CLASS_COLOR[c]}55` }}>{c}</button>
        ))}
      </div>

      <div className="flex flex-wrap gap-1 px-2 pt-2">
        {([
          ['TUBE', showTube, setShowTube],
          ['LINK', showLink, setShowLink],
          ['HALO', showHalo, setShowHalo],
          ['PIN', showPin, setShowPin],
          ['LBL', showLbl, setShowLbl],
          ['SINK', showSink, setShowSink],
        ] as Array<[string, boolean, (b:boolean)=>void]>).map(([label, on, set]) => (
          <button key={label} onClick={() => set(!on)}
            className={`px-1.5 py-0.5 rounded text-[10px] font-mono border transition ${on?'bg-sky-500/15 border-sky-500/40 text-sky-300':'border-slate-700 text-slate-500 hover:text-slate-300'}`}>{label}</button>
        ))}
      </div>

      <div className="px-2 pt-2">
        <input value={search} onChange={e => setSearch(e.target.value)} placeholder="callsign · icao · type · class"
          className="w-full bg-slate-900/60 border border-slate-800 rounded px-2 py-1 text-[11px] placeholder:text-slate-600 focus:outline-none focus:border-sky-500/50" />
      </div>
      <div className="grid grid-cols-3 gap-1 px-2 pt-2 text-[10px]">
        {(['ENCOUNTERS','LEADERS','CLASSES'] as const).map(t => (
          <button key={t} onClick={() => setTab(t)}
            className={`px-2 py-1 rounded border transition ${tab===t?'bg-sky-500/15 border-sky-500/40 text-sky-300':'border-slate-800 text-slate-400 hover:text-slate-200'}`}>{t}</button>
        ))}
      </div>

      <div className="flex-1 overflow-y-auto px-2 pt-2 pb-2 space-y-1.5">
        {tab === 'ENCOUNTERS' && visible.length === 0 && (
          <div className="text-center text-slate-600 text-[11px] pt-6">no wake encounters detected</div>
        )}
        {tab === 'ENCOUNTERS' && visible.map((e, i) => (
          <div key={i} className="rounded border border-slate-800 bg-slate-900/40 overflow-hidden cursor-pointer hover:border-slate-700"
            onClick={() => onFly(e.follower.icao)}>
            <div className="h-0.5" style={{ background: TIER_COLOR[e.tier] }} />
            <div className="p-2 space-y-1">
              <div className="flex items-center gap-1.5 text-[11px]">
                <span className="font-mono text-slate-300">{e.leader.callsign || e.leader.icao}</span>
                {classPill(e.leaderClass)}
                <span className="text-slate-500">›</span>
                <span className="font-mono font-semibold text-slate-100">{e.follower.callsign || e.follower.icao}</span>
                {classPill(e.followerClass)}
                {e.inTube && <span className="px-1 py-0.5 rounded text-[9px] font-mono bg-rose-500/20 text-rose-400 border border-rose-500/50">IN-TUBE</span>}
                <div className="ml-auto">{tierPill(e.tier)}</div>
              </div>
              <div className="flex items-center gap-2 text-[10px] font-mono text-slate-400">
                <span>trail <span className="text-slate-200">{e.inTrailNm.toFixed(1)}nm</span></span>
                <span>lat <span className="text-slate-200">{e.lateralOffsetNm>=0?'+':''}{e.lateralOffsetNm.toFixed(2)}nm</span></span>
                <span>Δh <span style={{ color: Math.abs(e.verticalOffsetFt) < 500 ? '#ef4444' : Math.abs(e.verticalOffsetFt) < 1000 ? '#f59e0b' : '#10b981' }}>{e.verticalOffsetFt>=0?'+':''}{Math.round(e.verticalOffsetFt)}ft</span></span>
                <span>age <span className="text-slate-200">{Math.round(e.ageS)}s</span></span>
              </div>
              <div className="flex items-center gap-2 text-[10px] font-mono text-slate-400">
                <span>v-tan <span style={{ color: TIER_COLOR[e.tier] }}>{Math.round(e.vTangentialKts)}kt</span></span>
                <span>Γ <span className="text-slate-200">{Math.round(e.gammaResid)}m²/s</span></span>
                <span>Cl <span style={{ color: TIER_COLOR[e.tier] }}>{e.rollingMomentCoef.toFixed(3)}</span></span>
                <span>sink <span className="text-slate-200">{Math.round(e.vortexSinkFt)}ft</span></span>
              </div>
              <div className="h-1 rounded bg-slate-800 overflow-hidden">
                <div className="h-full" style={{ width: `${e.score}%`, background: TIER_COLOR[e.tier] }} />
              </div>
              <div className="grid grid-cols-6 gap-0.5 text-[9px]">
                {(['gamma','geom','age','offset','alt','closing'] as const).map(k => (
                  <div key={k} className="rounded bg-slate-900/60 px-1 py-0.5 text-center" style={{ color: TIER_COLOR[e.tier] }}>
                    <div className="opacity-60">{k.slice(0,3).toUpperCase()}</div>
                    <div className="font-mono">{Math.round(e.drivers[k])}</div>
                  </div>
                ))}
              </div>
              <div className="text-[10px] leading-snug" style={{ color: TIER_COLOR[e.tier] }}>
                {e.rationale} <span className="text-slate-600 italic">· {e.citation}</span>
              </div>
            </div>
          </div>
        ))}

        {tab === 'LEADERS' && byLeader.length === 0 && (
          <div className="text-center text-slate-600 text-[11px] pt-6">no wake leaders</div>
        )}
        {tab === 'LEADERS' && byLeader.map(([icao, es]) => {
          const w = es[0]
          const sev = es.filter(x => x.tier==='SEVERE').length
          const mp = es.filter(x => x.tier==='MOD-PLUS').length
          const mod = es.filter(x => x.tier==='MODERATE').length
          return (
            <div key={icao} className="rounded border border-slate-800 bg-slate-900/40 overflow-hidden cursor-pointer hover:border-slate-700" onClick={() => onFly(icao)}>
              <div className="h-0.5" style={{ background: TIER_COLOR[w.tier] }} />
              <div className="p-2 space-y-1">
                <div className="flex items-center gap-1.5 text-[11px]">
                  <span className="font-mono font-semibold text-slate-100">{w.leader.callsign || icao}</span>
                  {classPill(w.leaderClass)}
                  <span className="text-slate-500 text-[10px] truncate">{w.leader.type}</span>
                  <div className="ml-auto">{tierPill(w.tier)}</div>
                </div>
                <div className="flex items-center gap-2 text-[10px] font-mono text-slate-400">
                  <span>FL{Math.round(w.leader.altitudeFt/100).toString().padStart(3,'0')}</span>
                  <span>{Math.round(w.leader.velocityKts)}kt</span>
                  <span>{es.length} follower{es.length!==1?'s':''}</span>
                  {sev > 0 && <span className="text-rose-400">SEV {sev}</span>}
                  {mp > 0 && <span className="text-rose-300">MP {mp}</span>}
                  {mod > 0 && <span className="text-amber-400">MOD {mod}</span>}
                </div>
                <div className="h-1 rounded bg-slate-800 overflow-hidden">
                  <div className="h-full" style={{ width: `${w.score}%`, background: TIER_COLOR[w.tier] }} />
                </div>
              </div>
            </div>
          )
        })}

        {tab === 'CLASSES' && byClass.length === 0 && (
          <div className="text-center text-slate-600 text-[11px] pt-6">no class data</div>
        )}
        {tab === 'CLASSES' && byClass.map(([c, es]) => {
          const mean = Math.round(es.reduce((s,e) => s + e.score, 0) / es.length)
          const tier: Tier = mean >= 75 ? 'SEVERE' : mean >= 55 ? 'MOD-PLUS' : mean >= 35 ? 'MODERATE' : mean >= 18 ? 'LIGHT' : 'TRACE'
          const sev = es.filter(x => x.tier==='SEVERE').length
          const mp = es.filter(x => x.tier==='MOD-PLUS').length
          const meanV = (es.reduce((s,e) => s + e.vTangentialKts, 0) / es.length).toFixed(1)
          return (
            <div key={c} className="rounded border border-slate-800 bg-slate-900/40 p-2 space-y-1">
              <div className="flex items-center gap-1.5 text-[11px]">
                {classPill(c)}
                <span className="text-slate-400 text-[10px]">b0 {WAKE_CLASS[c].b0.toFixed(1)}m · span {WAKE_CLASS[c].span}m</span>
                <div className="ml-auto">{tierPill(tier)}</div>
              </div>
              <div className="flex items-center gap-2 text-[10px] font-mono text-slate-400">
                <span>{es.length} pairs · {new Set(es.map(e => e.leader.icao)).size} leaders</span>
                <span>mean v-tan <span className="text-slate-200">{meanV}kt</span></span>
                {sev > 0 && <span className="text-rose-400">SEV {sev}</span>}
                {mp > 0 && <span className="text-rose-300">MP {mp}</span>}
              </div>
              <div className="h-1 rounded bg-slate-800 overflow-hidden">
                <div className="h-full" style={{ width: `${mean}%`, background: TIER_COLOR[tier] }} />
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
